#!/bin/python

import os
import subprocess

luser = os.getenv('USER')

#p = subprocess.Popen(['quota','-w'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

#out,err = p.communicate()

#lines = [b.strip() for b in out.split('\n')]

#print('\n\033[31m{0:>10}\033[0m'.format('Quotas for home, storage pool and shared project spaces'))
print('\n\033[31m{0:>10}\033[0m'.format('Quota for home directory'))
print('\n\033[1m{0:>30}  {1:10}  {2:10}  {3:10}\033[0m'.format('Storage','Usage (GB)','Quota (GB)','   % Used'))

#get user quotas
#for x in range(2,len(lines)-2):
#	lsplit = lines[x].replace(':',' ').split()
#	fsname = lsplit[1] + '/' + luser
#	q = lines[x].strip().split()
#	q1 = q[1].translate(None, '*')
#	q2 = q[2].translate(None, '*')
#	print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format(fsname,float(q1)/(1024**2), float(q2)/(1024**2),float(q1)/float(q2)))

#
#get xfs from quota logfile which is processed from cronjob on raapoi_fs01
#
#g = subprocess.Popen(['groups'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#out,err = g.communicate()
#groups = out.split()
qfile = open('/nfs/home/cad/log/quota.log', 'w')
for line in qfile:
    if luser in line:
      user,used,quota = line.split()
      print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format('/nfs/home/' + user,float(used)/(1024**2), float(quota)/(1024**2),float(used)/float(quota)))
print ""
print('\n\033[31m{0:>10}\033[0m'.format('Quota for scratch directory'))
print('\n\033[1m{0:>30}  {1:10}  {2:10}  {3:10}\033[0m'.format('Storage','Usage (GB)','Quota (GB)','   % Used'))
print ""
qfile = open('/nfs/home/cad/log/scratch.log', 'r')
for line in qfile:
    if luser in line:
      user,used,quota = line.split()
      print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format('/nfs/scratch/' + user,float(used)/(1024**2), float(quota)/(1024**2),float(used)/float(quota)))
print ""
#
