#!/bin/bash
##
#
RED='\033[0;31m'
NC='\033[0m'
echo ""
printf "${RED}VUW CLUSTER PARTITIONS${NC}\n"
sinfo -p quicktest
echo ""
sinfo -p bigmem
echo ""
sinfo -p main
echo ""
echo "NOTE: This utility is a wrapper for the Slurm command:"
echo '      sinfo -p main'
echo ""

exit 0

