#!/bin/bash
##
## List the queue in Sloan partitions
##
## Usage: sloanq -a|-p|-m

#-a all
#-p partition
#-m my partitions (default) based on groups membership
RED='\033[0;31m'
NC='\033[0m'
echo -e "\033[1m              JOBID PARTITION     NAME     USER STATE            TIME          NODES  NODELIST(REASON) \033[0m"
#printf "${RED}MY JOBS ON MAIN PARTITION${NC}\n"
squeue -l -h -u $USER -p main
#squeue -l -h -u $USER -p sched_sloan_batch
echo ""
echo "NOTE: This utility is a wrapper for the Slurm command:"
echo '      squeue -l -h -u $USER -p main'
echo ""
exit 0
