#!/bin/bash
##
#
RED='\033[0;31m'
NC='\033[0m'
echo ""
printf "${RED}VUW CLUSTER PARTITIONS${NC}\n"
sinfo -p quicktest
echo ""
# GPU nodes returned to ECS :(
#sinfo -p gpu
#echo ""
sinfo -p bigmem
echo ""
sinfo -p parallel
echo ""
echo "NOTE: This utility is a wrapper for the Slurm command:"
echo '      sinfo -p PARTITION'
echo ""

exit 0
