#!/bin/python

import os
import subprocess

luser = os.getenv('USER')

print('\n\033[31m{0:>10}\033[0m'.format('User Quotas'))
print('\n\033[1m{0:>30}  {1:10}  {2:10}  {3:10}\033[0m'.format('Storage','Usage (GB)','Quota (GB)','   % Used'))

#
qfile = open('/nfs/home/cad/log/quota.log', 'r')
for line in qfile:
    if luser in line:
      user,used,quota = line.split()
      print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format('/nfs/home/' + user,float(used)/(1024**2), float(quota)/(1024**2),float(used)/float(quota)))
print ""
qfile = open('/nfs/home/cad/log/scratch.log', 'r')
for line in qfile:
    if luser in line:
      user,used,quota = line.split()
      print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format('/nfs/scratch/' + user,float(used)/(1024**2), float(quota)/(1024**2),float(used)/float(quota)))
print ""
#
print('\n\033[31m{0:>10}\033[0m'.format('Group Quotas'))
print('\n\033[1m{0:>30}  {1:10}  {2:10}  {3:10}\033[0m'.format('Storage','Usage (GB)','Quota (GB)','   % Used'))
g = subprocess.Popen(['groups'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out,err = g.communicate()
groups = out.split()
qfile = open('/nfs/home/cad/log/group.log', 'r')
for line in qfile:
    group,used,quota = line.split()
    if group in groups:
      print('{0:>30}  {1:10.2f}  {2:10.2f} {3:10.2%}'.format('/nfs/scratch/' + group,float(used)/(1024**2), float(quota)/(1024**2),float(used)/float(quota)))
print ""
