#!/bin/bash
##
RED='\033[0;31m'
NC='\033[0m'
echo -e "\033[1m              JOBID PARTITION     NAME     USER STATE            TIME          NODES  NODELIST(REASON) \033[0m"
#printf "${RED}MY JOBS ON RAAPOI PARTITIONS${NC}\n"
squeue -l -h -u $USER -p quicktest
squeue -l -h -u $USER -p bigmem
squeue -l -h -u $USER -p parallel
echo ""
echo "NOTE: This utility is a wrapper for the Slurm command:"
echo '      squeue -l -h -u $USER -p PARTITION'
echo ""
exit 0
