#!/bin/bash
##
## List the queue in cluster partitions
##

RED='\033[0;31m'
NC='\033[0m'
printf "${RED}PARALLEL PARTITION QUEUE: parallel${NC}\n"
squeue -p parallel -o "%.15i %.16j %.10u %.7C %.7m %.12M %.12L %.10T %R"
echo ""
echo ""
printf "${RED}BIG MEMORY PARTITION QUEUE: bigmem${NC}\n"
squeue -p bigmem -o "%.15i %.16j %.10u %.7C %.7m %.12M %.12L %.10T %R"
echo ""
printf "${RED}QUICK TEST PARTITION QUEUE: quicktest (Default partition) ${NC}\n"
squeue -p quicktest -o "%.15i %.16j %.10u %.7C %.7m %.12M %.12L %.10T %R"
echo ""

#if [[ `groups` =~ .*sched_mit_thesmar* ]]; then
#  printf "${RED}DAVID THESMAR PARTITION QUEUE: sched_mit_thesmar${NC}\n"
#  squeue -p sched_mit_thesmar -o "%.15i %.8j %.10u %.7c %.7m %.6b %.12M %.12L %.10T %R"
#  #squeue -l -p sched_mit_thesmar
#fi
echo ""
echo "This utility is a wrapper for the Slurm command:"
echo 'squeue -p PARTITION -o "%.15i %.16j %.10u %.7c %.7m %.12M %.12L %.10T %R"'
echo ""
exit
