#!/bin/bash
d48=`date --date="5 days ago" +%Y-%m-%d`
printf "${RED}MY JOBS WITHIN LAST 5 days${NC}\n"
#sacct --format="JobID, State, MaxRSS, JobName, End" -S $d48 -s CD -s CA -s F
sacct --units=G --format="JobID, State, JobName, MaxVMSize, CPUTime" -S $d48 -s CD -s CA -s F
echo ""
echo "MaxVMSize represents the maximum memory used by your job.  You can use"
echo "this to help determine your future resource requests"
echo ""
echo "This command shows jobs within last 5 days, if you want to go further"
echo "back you can use the command sacct with a date, eg sacct -S 2017-04-01"
echo ""
echo "You can also use the vuw-job-report command to see more information about"
echo "a specific job"
echo ""
echo "NOTE: This utility is a wrapper for the Slurm command:"
echo '       sacct --units=G --format="JobID, State, JobName, MaxVMSize, CPUTime" -s CD -s CA -s F'
echo ""
exit 0
