#!/bin/bash
##
## Show a brief job report
##
if [ $# -lt 1 ]; then
  echo ""
  echo "Usage: vuw-job-report <JobID>"
  echo "   Eg: vuw-job-report 267895"
  echo ""
  exit 1
fi
GREEN='\033[0;32m'
NC='\033[0m'
printf "${GREEN}JOB REPORT FOR JOB $1${NC}\n"
echo ""
seff $1
echo ""
echo -e "\033[1m     JobName  Nodes    ReqMem   TotalMemUsed  ReqCPUs AllocCPUs    CPUTime     State    Completed \033[0m"
sacct --units=G  -j $1 --format="JobName,NNodes, ReqMem, MaxVMSize, ReqCPUS%9, AllocCPUS, TotalCPU%15, State, End" -n
echo ""
echo "# ReqMem output includes Requested Memory per Node (n) or per CPU (c), eg 2Gc is 2 GB per CPU"
echo ""
echo "# There may be a difference between Requested CPUs and Allocated CPUs."
echo "# This is due to hyperthreading being enabled on most nodes in the cluster.  If you request an odd number"
echo "# of CPUs you may be given an extra CPU so a CPU core is not shared between 2 different jobs. This will only"
echo "# occur if your job is run on a node with hyperthreading enabled.  This will also affect your memory allocation."
echo "# If you have any questions or concerns about hyperthreading and memory usage, please send a message to Slack"
echo ""
echo "NOTE: This utility is a wrapper for the Slurm commands:"
echo "seff <jobid>"
echo 'sacct --units=G -j $1 --format="JobName, NNodes, ReqMem, MaxVMSize, ReqCPUS%9, AllocCPUS, TotalCPU%15, State, End" -n'
echo ""
exit 0
